# Generated by Django 2.2.5 on 2021-12-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20211109_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bath',
            new_name='baths',
        ),
    ]
